#!/usr/bin/env bash
# Bash script for installing nginx web server with the configurations:
#   Listens on port 80.
#   Returns a page containing "Hello World!"
#   When queried at the root with curl GET request.

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
