#!/usr/bin/env bash
# Bash script for installing nginx web server with the configurations:
#   Listens on port 80.
#   Returns a page containing "Hello World!"
#   When queried at the root with curl GET request.

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
service nginx restart
