#!/usr/bin/env bash
# Debugs and Configures an Nginx server to listen on port 80.

service nginx stop
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
