#!/usr/bin/env bash
# Debugs and Configures an Nginx server to listen on port 80.
ln -sfn /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sed -i 's|pid /run/nginx.pid|pid /run/nginx_pid|' /etc/nginx/nginx.conf
