#!/usr/bin/env bash
# bash script that sorts the parsed
# apache data based on the following format:
# OCCURENCE_NUMBER IP HTTP_CODE
# In list format
# Ordered from the greatest to
# the lowest number of occurrences

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
